### PR TITLE
Removed useless php polyfills

### PR DESCRIPTION
**Pull request by aivchen**

### CODE REVIEW

**Comment by aivchen** [comment]
No, there is something else. I assume one of the used packages has been released recently. You can run CI on master branch and you will get the same error.

**Comment by dantleech** [comment]
when trying to install PHPBench on 8.2 I get: 
```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - phpbench/phpbench is present at version dev-master and cannot be modified by Composer
    - Only one of these can be installed: symfony/polyfill-php81[v1.28.0], phpbench/phpbench[dev-master]. phpbench/phpbench replaces symfony/polyfill-php81 and thus cannot coexist with it.
    - symfony/polyfill-php81 is locked to version v1.28.0 and an update of this package was not requested.


```

and now I'm confused why this PR was needed in the first place?

**Comment by aivchen** [comment]
Just follow composer advice ( as your composer.lock is not in sync with composer.json): `composer update`

Or remove composer.lock and run `composer install`.

I checked it on 8.1 and everything is working as expected.

>and now I'm confused why this PR was needed in the first place?

https://thecodest.co/blog/why-do-we-need-symfony-polyfill-and-why-we-shouldnt/

Given that phpbench minimal version requirement is 8.1 we don't need polyfills for 8.0 as php 8.1 already contains all functions defined in polyfill-8.0. Same for polyfill-8.1.

**Comment by dantleech** [comment]
hm, long day and seems I haven't run composer install for a long time, thanks!

**Comment by dantleech** [comment]
hm, I get this when trying to update a projecct to `dev-master`:

composer update                                        main ⬆ ✭ ✖ ✱ ◼
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "7.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - __root__ is present at version dev-main and cannot be modified by Composer
    - phpbench/phpbench[dev-master, 1.2.x-dev] cannot be installed as that would require removing __root__[dev-main]. They both replace symfony/polyfill-php81 and thus cannot coexist.
    - Root composer.json requires phpbench/phpbench dev-master -> satisfiable by phpbench/phpbench[dev-master].
 ```

it's a Symfony project that has:

```
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*",
        "symfony/polyfill-php82": "*"
    },
```

by default, removing these from the _client_ project "fixes" the issue, but I don't think that's a solution.

I'm going to revert this unless you think it's really important?

**Comment by dantleech** [comment]
https://github.com/phpbench/phpbench/pull/1099

**Pull request merged**
