### PR TITLE
Wraps template contents into immediately invoked functions

### PR DESCRIPTION
**Pull request by lmuzinic**
There was a variable name conflict between phpbench's $file in Remote/templates and our project's $file in config loader.

### CODE REVIEW

**Comment by dantleech** [comment]
Hmm, does this really work?

I was thinking more:

```php
<?php
// test.php

$foo = 'bar';
```

```php
$foo = 'hello';

function () {
    require_once('test.php');
};

echo $foo; // "hello"
```

**Comment by dantleech** [comment]
Would be great to add a regression test also - although not sure the best way to do that, as this issue is directly related to the script "template" files.

Perhaps for now it will be ok just to add a simple regression test [here](https://github.com/phpbench/phpbench/blob/master/tests/System/RunTest.php#L225) - and provide a bootstrap file which assigns `$file` to something else.

**Comment by lmuzinic** [comment]
OK, thanks for feedback. I'll refactor and add tests.

**Comment by dantleech** [comment]
Closing in favor of: https://github.com/phpbench/phpbench/pull/393

**Pull request closed without merging**
