### PR TITLE
[WIP] Add AppVeyor support

### PR DESCRIPTION
**Pull request by WyriHaximus**
Implements idea from #339

### CODE REVIEW

**Comment by dantleech** [comment]
Cool! Looks like we need to install the XSLT extension for PHP in the build process.

**Comment by WyriHaximus** [comment]
Hmm that is going to be interesting =D. php.ini manipulation from CLI on windows 0_o

**Comment by dantleech** [comment]
We did this before here: https://github.com/sulu/sulu/blob/develop/appveyor.yml Gussing it might be enough to do something similar.

**Comment by WyriHaximus** [comment]
Just realized while editing the file, it is already loading a few extensions that way :X

**Comment by dantleech** [comment]
Wow multiple issues. Looks like we need the PDO MySQL driver, then there are path problems and also a problem executing the PHPBench script to generate the test data (and I guess later to execute the system tests).

**Comment by WyriHaximus** [comment]
Nobody said it would be easy :stuck_out_tongue: . I'll look into it all of them, but it will take time and a lot of test commits :X

**Pull request closed without merging**
