### PR TITLE
Minor fix: Import `Attribute` symbol in `Format` and `RetryThreshold` Attributes

### PR DESCRIPTION
**Pull request by gsteel**

### CODE REVIEW

**Comment by dantleech** [comment]
oops, was this not working ?!

**Comment by gsteel** [comment]
It works fine @dantleech, but if you're using Psalm/PHPStan, they complain that the attributes aren't attributes!

**Comment by dantleech** [comment]
somehow some CS issues need fixing

**Comment by dantleech** [comment]
Thanks!

**Pull request merged**
