### PR TITLE
Add utf-8 charset to html report

### PR DESCRIPTION
**Pull request by johnrazeur**
Add utf-8 to html report.
See #519

### CODE REVIEW

**Comment by dantleech** [comment]
Thanks!

**Comment by dantleech** [comment]
Oops, this PR should have been made against `develop`

**Comment by dantleech** [comment]
Cherry-picked to master

**Comment by dantleech** [comment]
It turns out that the report is `XHTML` and not `html 5` (and the tests failed accordingly). Updated in https://github.com/phpbench/phpbench/commit/f3679135987a6c17494f289f612311d3998595bf please verify that this still works for you.

**Comment by johnrazeur** [comment]
I just test it. Works fine for me !

**Pull request merged**
