### PR TITLE
Add support for annotations 2

### PR DESCRIPTION
**Pull request by greg0ire**
It should allow other packages to add support for `doctrine/lexer` 3

### CODE REVIEW

**Comment by greg0ire** [comment]
Obviously, I need to look into this more in depth :sweat_smile:

**Comment by dantleech** [comment]
Might be worth dropping 7.3/4 support if this is tricky.

**Comment by greg0ire** [comment]
Just noticed removing php-cs-fixer allows me to reproduce errors locally (it requires annotations as well, so that makes sense).

**Comment by dantleech** [comment]
https://github.com/phpbench/phpbench/pull/1015/commits/eb95d026b49f334031f1e846c0e7b28c51958b37

seems to fix the build

**Comment by dantleech** [comment]
Thanks @greg0ire

**Pull request merged**
