### PR TITLE
Add support for symfony 7

### PR DESCRIPTION
**Pull request by keulinho**
Symfony released first beta of symfony 7, so we should support it as well

### CODE REVIEW

**Comment by keulinho** [comment]
For reference: https://github.com/phpbench/container/pull/11

**Comment by dantleech** [comment]
I've fixed the CS in master, can you rebase?

**Comment by keulinho** [comment]
Sorry i accidentally merged the master over the Github UI, i can also rebase and force push to this branch if you prefer.

**Comment by dantleech** [comment]
nah, it's fine :+1:

**Comment by keulinho** [comment]
Hey @dantleech symfony 7 is to be released this month, any chance we can get a release where this commit is included?

**Comment by dantleech** [comment]
well, the CI isn't running with it yet, so it's not really tested with Symfony 7....

**Comment by keulinho** [comment]
Hey @dantleech [symfony 7 is released](https://github.com/symfony/symfony/releases/tag/v7.0.0) so CI should now run with it as well :v:

When can we expect a release?

**Comment by dantleech** [comment]
i've tagged 1.2.15 :tada:

**Comment by keulinho** [comment]
Thanks :blue_heart:

**Pull request merged**
