### PR TITLE
If \PhpBench\Executor\Method\ErrorHandlingExecutorDecorator throws unhandled exception now is a bit clearer why

### PR DESCRIPTION
**Pull request by MekDrop**
3rd exception parameter $throwable can be used to get original exception. 

I think it could be useful when debugging exceptions.

### CODE REVIEW

**Review by dantleech — APPROVED** [review]

**Comment by dantleech** [comment]
yep, good call

**Comment by MekDrop** [comment]
@dantleech any idea why tests are failing? I tried to look into but I can't say that I see something there related to my changes :| Should I do something?

**Comment by dantleech** [comment]
hm, no it seems there are no failures just warnings? not sure why that behvior would have changed.

**Comment by dantleech** [comment]
sorry this got lost, thanks!

**Pull request merged**
