### PR TITLE
[WIP] Added variants index (from ParamProviders) to XML and table generators

### PR DESCRIPTION
**Pull request by WyriHaximus**
Follow up PR from [this](https://twitter.com/WyriHaximus/status/762747733925064704) twitter conversation. Currently this is a first try and I might have broken things horribly. In any case I'm looking forward to your feedback

### CODE REVIEW

**Comment by dantleech** [comment]
Is the aim to show an index for each parameter variation? e.g.

```
1. { foobar: bar, barfoo: foo }
2. { foobar: foo, barfoo: bar }
```

In this case I think we can reuse the existing `ParameterSet#getIndex` without neededing a separate `$index`.

I would change the XML attribute name to something like `parameter-set-index` - as a variant could vary on things other than parameters (e.g. nb revolutions, iterations etc).

The report renderers can then show the `parameter-set-index` when an noption is present (`param_indexes`?) and automatically show a legend above the report.

**Comment by dantleech** [comment]
Sorry the tests fail. Its because of the automatic building of the PHAR. I need to fix that to allow 3rd party builds. Locally it is sufficient to just run `phpunit`.

**Comment by WyriHaximus** [comment]
The aim is to display the key from a [`ParamProviders`](https://github.com/php-api-clients/hydrator/blob/master/benchmarks/HydratorBench.php#L25-L70) as shown [here](https://travis-ci.org/php-api-clients/hydrator/jobs/151952601#L506-L521). Not sure if my current approach is the best approach, it is  rather a quick and easy 'lets see how far I can get'. So if you have a better way of doing this I rather take that road :). If not I'll continue on this one

**Comment by dantleech** [comment]
Ah I see what you are doing now. I'm not sure how that approach works with matrix situations: http://phpbench.readthedocs.io/en/latest/writing-benchmarks.html#parameterized-benchmarks

In a matrix scenario you could have several parameter providers. So the key of the parameter set is numeric and depends on the number of parameter providers. You could I guess generate composite keys (e.g. `algorithm_one / engine_two / factor_five`).

I was thinking more of:

```
PhpBench 0.12-dev (@git_version@). Running benchmarks.
Using configuration file: /home/daniel/www/phpbench/phpbench/phpbench.json

\PhpBench\Micro\Math\StatisticsBench

    benchVariance                 I9 P0         [μ Mo]/r: 10.33 10.25 (μs)      [μSD μRSD]/r: 0.332μs 3.21%
    benchStDev                    I9 P0         [μ Mo]/r: 12.66 12.56 (μs)      [μSD μRSD]/r: 0.588μs 4.65%

2 subjects, 20 iterations, 200 revs, 0 rejects
(best [mean mode] worst) = 9.660 [11.493 11.407] 10.800 (μs)
⅀T: 229.860μs μSD/r 0.460μs μRSD/r: 3.931%
suite: 133a12d1287cb0704f768b0affe3dcebc9b972e2, date: 2016-08-13, stime: 09:59:22

{1} { foobar: 12, barfoo: "bar", "resources: [ "one": { "bar": 12 } ] }
{2} { foobar: 24, barfoo: "foo", "resources: [ "two": { "bar": 32 } ] }
{3} { foobar: .., barfoo: "...", "resources: [ "...": { "bar": .. } ] }

+-----------------+---------------+--------+-------- +------+------+----------+----------+--------------+----------------+
| benchmark       | subject       | groups | param # | revs | iter | mem_peak | time_rev | comp_z_value | comp_deviation |
+-----------------+---------------+--------+-------- +------+------+----------+----------+--------------+----------------+
| StatisticsBench | benchVariance |        | 1       | 100  | 0    | 942,184b | 10.41μs  | +0.24σ       | +0.78%         |
| StatisticsBench | benchVariance |        | 2       | 100  | 1    | 942,184b | 10.80μs  | +1.42σ       | +4.56%         |
| StatisticsBench | benchVariance |        | 3       | 100  | 2    | 942,184b | 10.11μs  | -0.66σ       | -2.12%         |
```

But not sure how useful that is in your case.

**Pull request closed without merging**
